### ISSUE TITLE
패키지 매니저를 통해 다운로드하는 방식

### ISSUE THREAD

**Issue by inertiave** [madumpa/URP_StylizedLitShader#1]
안녕하세요.

혹, 패키지 매니저를 통해 다운로드할 수 있도록 패키지화할 계획이 있으신가요?
아직 없으시다면 PR을 해보려고합니다. 
main 브랜치가 아닌 package manager를 위한 다른 브랜치에 머지해주실 계획이 있으신지 궁금합니다.

감사합니다.

**Comment by madumpa** [comment]
안녕하세요. 

패키지 매니저를 통해 다운로드 할 수 있도록 하면 보다 편리하겠군요.
아직 생각해본 적은 없지만 그렇게 해 두면 편리할것같아서 조만간 말씀하신대로 업데이트를 해 보도록 하겠습니다. 
(PR은 어떤 PR을 말씀하시는건지 제가 깃허브 초보라 잘 모르겠네요. 패키지 릴리즈나 프로젝트 리뷰 같은건가요?)

좋은 아이디어 감사합니다.

**Comment by inertiave** [comment]
딥변 감사합니다

PR은 상단 탭 메뉴중에 보실 수 있듯이 풀 리퀘스트를 말합니다. 
누군가 이 리포지토리에 기여를 할 수 있게 되는 기능입니다.

계획이 있으시다니 기다리도록 하겠습니다.
양질의 자료 감사드립니다.

**Comment by madumpa** [comment]
PR이 풀 리퀘스트였다는것을 뒤늦게 알게 되었네요 ㅎㅎ; 

계획은 있지만 언제할지 모르기때문에 (..) PR해 주신다면 별도의 브랜치에 머지해보도록 하겠습니다. 감사합니다

**Comment by inertiave** [comment]
제가 쓰려고 생성한 패키지 버전 브랜치가 있습니다.

https://github.com/cqtd/URP_StylizedLitShader/tree/package-manager
PR을 하려고 하니 아직 main 브랜치 밖에 없어 PR을 넣지 않았습니다.
적당한 이름의 브랜치를 만들어주시면 PR 요청을 하겠습니다.

Scene은 Package에 포함되어있을 때 열리지가 않게 되어있어 Sample로 빼었습니다.

**Comment by madumpa** [comment]
packageManagerWork 라는 브랜치를 만들어 두었습니다
이쪽에 PR을 넣어주시면 리뷰하도록 하겠습니다 
감사합니다!
